In [29]:
import pandas as pd

In [30]:
dict = {
         "name" : ["sujal", "ram", "shyamdulari", "ramkhelawan","jitin", "sameer", "raj", "ramesh", "suresh", "vimal", "GEETA"],
          "age" : [23,56,85,12,45,36,25,26,24,45,15],
          "gender" : ["M", "M","F", "M", "M", "M","M", "M","M", "M","F"]
}

In [31]:
df = pd.DataFrame(dict)

In [32]:
df

           name  age gender
0         sujal   23      M
1           ram   56      M
2   shyamdulari   85      F
3   ramkhelawan   12      M
4         jitin   45      M
5        sameer   36      M
6           raj   25      M
7        ramesh   26      M
8        suresh   24      M
9         vimal   45      M
10        GEETA   15      F

In [33]:
df.head(5)

          name  age gender
0        sujal   23      M
1          ram   56      M
2  shyamdulari   85      F
3  ramkhelawan   12      M
4        jitin   45      M

In [34]:
df.tail(6)

      name  age gender
5   sameer   36      M
6      raj   25      M
7   ramesh   26      M
8   suresh   24      M
9    vimal   45      M
10   GEETA   15      F

In [35]:
df.shape[1]

3

In [36]:
df.info

<bound method DataFrame.info of            name  age gender
0         sujal   23      M
1           ram   56      M
2   shyamdulari   85      F
3   ramkhelawan   12      M
4         jitin   45      M
5        sameer   36      M
6           raj   25      M
7        ramesh   26      M
8        suresh   24      M
9         vimal   45      M
10        GEETA   15      F>

In [37]:
df.isnull

<bound method DataFrame.isnull of            name  age gender
0         sujal   23      M
1           ram   56      M
2   shyamdulari   85      F
3   ramkhelawan   12      M
4         jitin   45      M
5        sameer   36      M
6           raj   25      M
7        ramesh   26      M
8        suresh   24      M
9         vimal   45      M
10        GEETA   15      F>

In [38]:
df.isnull().sum()

name      0
age       0
gender    0
dtype: int64

In [39]:
df.describe()

             age
count  11.000000
mean   35.636364
std    21.242753
min    12.000000
25%    23.500000
50%    26.000000
75%    45.000000
max    85.000000

In [40]:
df["age"].unique()

array([23, 56, 85, 12, 45, 36, 25, 26, 24, 15])

In [41]:
df["age"].nunique()

10

In [42]:
df['gender'].value_counts()

gender
M    9
F    2
Name: count, dtype: int64

In [43]:
df['age'].between(20,45).value_counts()

age
True     7
False    4
Name: count, dtype: int64

In [44]:
print(df['age'].min()   )

12

In [45]:
print(df['age'].max()   )

85

In [46]:
print(df['age'].mean()   )

35.63636363636363

In [47]:
df['half_age'] = df['age'].apply(lambda x: x/2)

In [48]:
df

           name  age gender  half_age
0         sujal   23      M      11.5
1           ram   56      M      28.0
2   shyamdulari   85      F      42.5
3   ramkhelawan   12      M       6.0
4         jitin   45      M      22.5
5        sameer   36      M      18.0
6           raj   25      M      12.5
7        ramesh   26      M      13.0
8        suresh   24      M      12.0
9         vimal   45      M      22.5
10        GEETA   15      F       7.5

In [49]:
df['gen'] = df['gender'].map({'M': 'Male', 'F': 'Female'})

In [50]:
df

           name  age gender  half_age     gen
0         sujal   23      M      11.5    Male
1           ram   56      M      28.0    Male
2   shyamdulari   85      F      42.5  Female
3   ramkhelawan   12      M       6.0    Male
4         jitin   45      M      22.5    Male
5        sameer   36      M      18.0    Male
6           raj   25      M      12.5    Male
7        ramesh   26      M      13.0    Male
8        suresh   24      M      12.0    Male
9         vimal   45      M      22.5    Male
10        GEETA   15      F       7.5  Female

In [51]:
df.drop("gen", axis=1)

           name  age gender  half_age
0         sujal   23      M      11.5
1           ram   56      M      28.0
2   shyamdulari   85      F      42.5
3   ramkhelawan   12      M       6.0
4         jitin   45      M      22.5
5        sameer   36      M      18.0
6           raj   25      M      12.5
7        ramesh   26      M      13.0
8        suresh   24      M      12.0
9         vimal   45      M      22.5
10        GEETA   15      F       7.5

In [52]:
df.sort_values(by="age", ascending=False)

           name  age gender  half_age     gen
2   shyamdulari   85      F      42.5  Female
1           ram   56      M      28.0    Male
4         jitin   45      M      22.5    Male
9         vimal   45      M      22.5    Male
5        sameer   36      M      18.0    Male
7        ramesh   26      M      13.0    Male
6           raj   25      M      12.5    Male
8        suresh   24      M      12.0    Male
0         sujal   23      M      11.5    Male
10        GEETA   15      F       7.5  Female
3   ramkhelawan   12      M       6.0    Male